function MAGSIGN = readTLA5202data(datafilename)
%This part reads the data file generated by TLA5202.
prompt={'Enter the TLA5202 txt data file name'};
Title='1st step';
DefAns=datafilename;

LineNo=1;
answer=inputdlg(prompt,Title,LineNo,DefAns);
efilename=answer{1};

fid1=fopen(efilename,'r');

MAGSIGN0=[];
MAGSIGN1=[];
MAGSIGN2=[];
MAGSIGN3=[];
MAGSIGN4=[];
MAGSIGN5=[];
MAGSIGN6=[];
MAGSIGN7=[];
CLKtime=[];
%This part only reads all the information contained in the data file into memory, 
EpochNumber=0;
temp=fscanf(fid1,'%s',5);
temp=fscanf(fid1,'%d',2);
while ~isempty(temp)
    EpochNumber = EpochNumber+1
    tempMAG=fscanf(fid1,'%d',1);
    tempSIGN=fscanf(fid1,'%d',1);
    if (tempMAG==1)
        temp = 3;
    else
        temp = 1;
    end
    if (tempSIGN==0)
        temp = -temp;
    end
    k = floor(EpochNumber/100000);
    switch(k)
        case 0
            MAGSIGN0 = [MAGSIGN0 temp];
        case 1
            MAGSIGN1 = [MAGSIGN1 temp];
        case 2
            MAGSIGN2 = [MAGSIGN2 temp];
        case 3
            MAGSIGN3 = [MAGSIGN3 temp];
        case 4
            MAGSIGN4 = [MAGSIGN4 temp];
        case 5
            MAGSIGN5 = [MAGSIGN5 temp];
        case 6
            MAGSIGN6 = [MAGSIGN6 temp];
        case 7
            MAGSIGN7 = [MAGSIGN7 temp];
        otherwise
            disp('prolong MAGSIGN7');
    end
            
    temp=fscanf(fid1,'%f',1);
%     if (EpochNumber==1)
%         CLKtime = [CLKtime temp];
%     else
%         CLKtime = [CLKtime temp+CLKtime(EpochNumber-1)];
%     end
    temp=fscanf(fid1,'%s',1);
    temp=fscanf(fid1,'%d',2);
end
fclose(fid1);
MAGSIGN = [MAGSIGN0 MAGSIGN1 MAGSIGN2 MAGSIGN3 MAGSIGN4 MAGSIGN5 MAGSIGN6 MAGSIGN7];
save TLA5202 MAGSIGN;
