-- ProjNav VHDL simulation template: ca_code_nco_tbw.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
