source {C:/Xilinx91i/data/projnav/scripts/VsimStopServer.tcl}
-- Auto Generated by Project Navigator to simulate
-- HDL Bencher Annotated Test Bench
--
vlib work
onbreak {resume}
onerror {quit -code 99 -force}
onElabError {resume}
vcom -explicit  -93 "VHDLsource/intimer.vhd"
vcom -explicit  -93 "intimer_tbw.ant"
vsim -t 1ps   -lib work intimer_tbw
run -all
quit -force
